version: "2"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:4.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
